using Microsoft.EntityFrameworkCore;
using System.Net.Http.Json;
using System.Text;
using System.Text.Json;
using TSPMaster.API.Data;
using TSPMaster.API.Dtos.Analysis;
using TSPMaster.API.Models;

namespace TSPMaster.API.Services;

public class AnalysisService : IAnalysisService
{
    private static readonly string[] CoreFunds = ["G Fund", "F Fund", "C Fund", "S Fund", "I Fund"];

    private readonly ApplicationDbContext _db;
    private readonly ITspDataService _tspData;
    private readonly IConfiguration _config;
    private readonly IHttpClientFactory _httpClientFactory;
    private readonly ILogger<AnalysisService> _logger;

    public AnalysisService(
        ApplicationDbContext db,
        ITspDataService tspData,
        IConfiguration config,
        IHttpClientFactory httpClientFactory,
        ILogger<AnalysisService> logger)
    {
        _db = db;
        _tspData = tspData;
        _config = config;
        _httpClientFactory = httpClientFactory;
        _logger = logger;
    }

    public async Task<AnalysisResultDto?> GetLatestRecommendationAsync()
    {
        var result = await _db.AnalysisResults
            .Where(a => a.IsActive)
            .OrderByDescending(a => a.GeneratedAt)
            .FirstOrDefaultAsync();

        return result is null ? null : MapToDto(result);
    }

    public async Task<AnalysisResultDto> RefreshRecommendationAsync()
    {
        // Deactivate previous results
        var previous = await _db.AnalysisResults.Where(a => a.IsActive).ToListAsync();
        foreach (var p in previous) p.IsActive = false;

        // Gather 6 months of fund price data
        var to = DateOnly.FromDateTime(DateTime.UtcNow);
        var from = to.AddDays(-180);
        var allHistory = await _tspData.GetAllFundsHistoryAsync(from, to);

        // Compute statistical metrics for core funds
        var fundScores = new List<FundScoreDto>();
        var trendsBuilder = new StringBuilder();

        foreach (var fund in CoreFunds)
        {
            if (!allHistory.TryGetValue(fund, out var history) || history.Count < 2)
                continue;

            var prices = history.Select(h => (double)h.Price).ToArray();

            // Momentum: % return over period
            double momentum = (prices[^1] - prices[0]) / prices[0] * 100.0;

            // Volatility: standard deviation of daily returns
            var dailyReturns = prices.Zip(prices.Skip(1), (a, b) => (b - a) / a).ToArray();
            double mean = dailyReturns.Average();
            double variance = dailyReturns.Select(r => Math.Pow(r - mean, 2)).Average();
            double stddev = Math.Sqrt(variance) * 100.0;

            // 20-day and 50-day moving averages (if enough data)
            double ma20 = prices.Length >= 20 ? prices[^20..].Average() : prices.Average();
            double ma50 = prices.Length >= 50 ? prices[^50..].Average() : prices.Average();

            // Simple composite score (higher momentum, lower volatility = better)
            double score = momentum - (stddev * 0.5);
            string trend = prices[^1] > ma20 && ma20 > ma50 ? "Uptrend"
                         : prices[^1] < ma20 && ma20 < ma50 ? "Downtrend"
                         : "Sideways";

            trendsBuilder.AppendLine($"{fund}: 6-month return={momentum:F2}%, volatility={stddev:F2}%, 20-day MA={ma20:F4}, trend={trend}");

            fundScores.Add(new FundScoreDto(
                fund,
                Math.Round(score, 2),
                trend,
                Math.Round(momentum, 2),
                Math.Round(stddev, 2),
                string.Empty  // filled in by AI
            ));
        }

        var topFund = fundScores.OrderByDescending(f => f.Score).FirstOrDefault()?.FundName ?? "G Fund";

        // Call Gemini API
        var geminiApiKey = _config["Gemini:ApiKey"];
        var geminiModel = _config["Gemini:Model"] ?? "gemini-3.6-flash";
        string recommendationText;
        string marketContext = "Market context analysis generated by Google Gemini.";

        if (!string.IsNullOrEmpty(geminiApiKey) && geminiApiKey != "REPLACE_WITH_GEMINI_API_KEY")
        {
            var prompt = BuildGeminiPrompt(trendsBuilder.ToString(), topFund, fundScores);
            (recommendationText, marketContext) = await CallGeminiAsync(geminiApiKey, geminiModel, prompt);
        }
        else
        {
            _logger.LogWarning("Gemini API key not configured. Using statistical analysis only.");
            recommendationText = BuildFallbackRecommendation(fundScores, topFund);
        }

        // Update fund scores with AI recommendations
        var updatedScores = fundScores.Select(fs =>
            fs with { Recommendation = topFund == fs.FundName ? "Strong Buy" : fs.Score > 0 ? "Hold" : "Underweight" }
        ).ToList();

        // Persist result
        var analysisResult = new AnalysisResult
        {
            GeneratedAt = DateTime.UtcNow,
            PeriodDescription = "6 months",
            TopRecommendation = topFund,
            RecommendationText = recommendationText,
            FundScoresJson = JsonSerializer.Serialize(updatedScores),
            MarketContext = marketContext,
            IsActive = true
        };

        _db.AnalysisResults.Add(analysisResult);
        await _db.SaveChangesAsync();

        return MapToDto(analysisResult);
    }

    private async Task<(string recommendation, string marketContext)> CallGeminiAsync(
        string apiKey, string model, string prompt)
    {
        var url = $"https://generativelanguage.googleapis.com/v1beta/models/{model}:generateContent?key={apiKey}";
        var client = _httpClientFactory.CreateClient();

        var requestBody = new
        {
            contents = new[]
            {
                new
                {
                    parts = new[] { new { text = prompt } }
                }
            },
            generationConfig = new
            {
                temperature = 0.3,
                maxOutputTokens = 1024
            }
        };

        try
        {
            var response = await client.PostAsJsonAsync(url, requestBody);
            var json = await response.Content.ReadAsStringAsync();
            using var doc = JsonDocument.Parse(json);
            var text = doc.RootElement
                .GetProperty("candidates")[0]
                .GetProperty("content")
                .GetProperty("parts")[0]
                .GetProperty("text")
                .GetString() ?? string.Empty;

            // Split the response: first paragraph is recommendation, rest is context
            var lines = text.Split('\n', StringSplitOptions.RemoveEmptyEntries);
            var context = lines.Length > 3 ? string.Join("\n", lines.Skip(3)) : "See full recommendation above.";
            return (text, context);
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "Gemini API call failed.");
            return (BuildFallbackRecommendation([], string.Empty), "Analysis unavailable.");
        }
    }

    private static string BuildGeminiPrompt(string trendsData, string topFund, List<FundScoreDto> scores)
    {
        return $"""
            You are an expert TSP (Thrift Savings Plan) investment advisor for US federal employees.
            
            Analyze the following 6-month fund performance data and provide a clear, actionable investment recommendation.
            Focus on current market conditions, price trends, momentum, and volatility.
            
            **Fund Statistical Analysis (6-month period):**
            {trendsData}
            
            **Statistical Top Performer:** {topFund}
            
            Please provide:
            1. A clear recommendation for which fund(s) to invest in and why
            2. Brief reasoning for each core fund (G, F, C, S, I)
            3. Any cautions about market risks or volatility
            4. A suggested allocation strategy (e.g., "60% C Fund, 20% S Fund, 20% G Fund")
            
            Format your response in clear markdown with sections. Keep it under 400 words.
            Remember: TSP investors are typically long-term retirement investors (government employees).
            """;
    }

    private static string BuildFallbackRecommendation(List<FundScoreDto> scores, string topFund)
    {
        var sb = new StringBuilder();
        sb.AppendLine("## TSP Investment Analysis");
        sb.AppendLine();
        sb.AppendLine($"**Top Recommendation: {topFund}**");
        sb.AppendLine();
        sb.AppendLine("Based on 6-month historical price trends, momentum, and volatility analysis:");
        sb.AppendLine();

        foreach (var score in scores.OrderByDescending(s => s.Score))
        {
            sb.AppendLine($"- **{score.FundName}**: {score.Trend} | 6-mo return: {score.MomentumScore:+0.00;-0.00}% | Volatility: {score.VolatilityScore:F2}%");
        }

        sb.AppendLine();
        sb.AppendLine("> *This is a statistical analysis only. Past performance does not guarantee future results. Consider consulting a financial advisor before making investment decisions.*");

        return sb.ToString();
    }

    private static AnalysisResultDto MapToDto(AnalysisResult result)
    {
        var scores = new List<FundScoreDto>();
        try
        {
            scores = JsonSerializer.Deserialize<List<FundScoreDto>>(result.FundScoresJson) ?? [];
        }
        catch { /* ignore deserialization errors */ }

        return new AnalysisResultDto(
            result.Id,
            result.GeneratedAt,
            result.PeriodDescription,
            result.TopRecommendation,
            result.RecommendationText,
            scores,
            result.MarketContext
        );
    }
}
